language: rust
cache: cargo
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
